### ISSUE TITLE
Installation failed: 

### ISSUE THREAD

**Issue by HugoKlepsch** [Hyperz/plasmahimawari#2]
I cloned your repo, and ran 
`zip -r plasmahimawari-master.zip ./plasmahimawari`
which seemed to work (added files)
then when I ran 
`plasmapkg2 -t wallpaperplugin -i plasmahimawari-master.zip`

it printed 
`No metadata file in package "/home/hugo/plasmahimawari/plasmahimawari-master.zip" "/tmp/plasmapkg2-QWEJDk/"
Error: Installation of /home/hugo/plasmahimawari/plasmahimawari-master.zip failed: No metadata file in package: /home/hugo/plasmahimawari/plasmahimawari-master.zip`

**Comment by Hyperz** [comment]
If you open the zip file in Ark does the file structure look like this? 
![snapshot](https://cloud.githubusercontent.com/assets/1051702/12858965/7345e438-cc53-11e5-9693-9fa7939224fc.png)

It sounds like plasmapkg2 can't locate the `metadata.desktop` file. If you upload your zip file I can take a look.

**Comment by HugoKlepsch** [comment]
I should note here that I downloaded the zip from github here:
![download zip](https://cloud.githubusercontent.com/assets/12129001/12863931/4ef19aac-cc4c-11e5-9b91-c2e1187ad1be.png)
and here is the contents of it:
![plasmahimawari](https://cloud.githubusercontent.com/assets/12129001/12863936/5cd7a292-cc4c-11e5-99d9-8bff7fa934ed.png)

**Comment by HugoKlepsch** [comment]
User error! I should not have dl'd from the above button. I didn't know zip -r would make a zip. Instead I cloned it, made the zip and installed it no problem.
